### PR TITLE
Update Dockerfile by uninstall enum34

### PR DESCRIPTION
**Pull request by mnguyen0226**
## What?
[Describe what was changed and reference relevant issue.]
This modification related to the issue when install Docker for SMAC: https://github.com/instadeepai/Mava/issues/282

I tried to install Docker to both Python 3.6 and Python 3.7 and figure out that pysc2 needed as well as uninstall enum34 is needed before pip install oxwhiri/smac github repo to prevent enum-Python 3.6 error. Note that there are suggestion for update enum instead of uninstall but this will not work

## Why?
[Describe why the change was made.]
To be able to install Docker on Python 3.6, 3.7 correctly

## How?
[Describe how the change was made i.e. describe technically what the change does.]
Shown below

## Extra
[Any extra information.]
Also, I suggested to update the main Docker repo to up-to-date with the develop one since it does not have uninstall enum and it cause problem in install Docker.

I know that develop is a default git clone but many user might still try to use main branch instead

### CODE REVIEW

**Comment by DriesSmit** [comment]
Thanks for the PR @mnguyen0226 ! @KaleabTessera does these changes seem fine?

**Comment by KaleabTessera** [comment]
Thanks for your first PR @mnguyen0226 ! I am happy to accept the dockerfile changes, but we can't add the SMAC binaries. 

Can you please either create a new PR with just the dockerfile changes or remove the binary file changes & example changes from this PR ?

**Comment by mnguyen0226** [comment]
@KaleabTessera  Awesome! I have made a new pull request accordingly.

**Comment by KaleabTessera** [comment]
Duplicate of https://github.com/instadeepai/Mava/pull/286 .

**Pull request closed without merging**
