### PR TITLE
Chore: Rename jax file under utils folder

### PR DESCRIPTION
**Pull request by WiemKhlifi**
## What?
Rename` jax.py `to `jax_utils.py` under the `mava/utils` folder
## Why?
Avoid **_circular_** imports problem.

### CODE REVIEW

**Review by OmaymaMahjoub — CHANGES_REQUESTED** [review]
If you can also rename the import in the quickstart notebook :pray:

**Review by RuanJohn — DISMISSED** [review]
Thanks @WiemKhlifi :raised_hands:

**Review by OmaymaMahjoub — APPROVED** [review]
Thanks @WiemKhlifi

**Review by RuanJohn — APPROVED** [review]
Thank you!

**Pull request merged**
