### PR TITLE
Add return metrics for experiments and corresponding Hydra config option

### PR DESCRIPTION
**Pull request by liamclarkza**
## What?
We now return a performance evaluation metric from our experiment.

## Why?
Allows for us to hyperparameter tune using Hydra & OpTuna.

## How?
Modifies the run_experiment method and hydra_entry_point in the various systems to return a metric to be used for hyperparameter tuning through Hydra (using something like OpTuna). The Hydra config option, config.env.eval_metric,is used to select the metric (episode_return or win_rate) for an environment.

### CODE REVIEW

**Comment by EdanToledo** [comment]
LGTM

**Review by sash-a — DISMISSED** [review]
Looks great @liamclarkza, awesome first PR :fire:

**Review by RuanJohn — CHANGES_REQUESTED** [review]
Really epic first PR @liamclarkza :fire: 

Just a small detail from my side. Right now, this will return the evaluator output of the absolute metric evaluator. Can we please change it so that we return the results from the final online evaluation run?

**Review by RuanJohn — APPROVED** [review]
Thank you for this @liamclarkza! :fire:

**Review by EdanToledo — APPROVED** [review]

**Pull request merged**
