### PR TITLE
fix: use new vault api

### PR DESCRIPTION
**Pull request by callumtilbury**
## What?
Use the new (proposed) Vault API, with some minor changes.

## Why?
For it to work :^)

## How?
Simple changes.

## Extra
n/a

### CODE REVIEW

**Review by sash-a — DISMISSED** [review]
LGTM :shield:

**Review by WiemKhlifi — CHANGES_REQUESTED** [review]
The changes LGTM but I have a few suggestions unrelated to these and I can't add comments there 😅 
1- Update the network: This folder wasn't updated I guess to use the actor and critic from the network.py ( I can help with that).
2- This line was repeated twice I guess it's the default merge's fault:
```python
# Allow dynamic attributes.
  OmegaConf.set_struct(cfg, False)
```

**Comment by callumtilbury** [comment]
Well spotted, thanks @WiemKhlifi!

**Review by sash-a — APPROVED** [review]
Nice spot @WiemKhlifi

**Review by WiemKhlifi — APPROVED** [review]
Thanks guys this LGTM 🥳

**Pull request merged**
