### PR TITLE
chore: remove neptune project argument from system level logger configs

### PR DESCRIPTION
**Pull request by RuanJohn**
## What?
Only set the Neptune project name in the base logger config.

### CODE REVIEW

**Review by sash-a — DISMISSED** [review]
:rabbit:

**Review by sash-a — APPROVED** [review]
:rabbit2:

**Review by OmaymaMahjoub — CHANGES_REQUESTED** [review]
Can we keep neptune tag per system? because when you run a sweep you want each of the system have a different tag automatically without the need to set neptune tag in the cmd

**Comment by OmaymaMahjoub** [comment]
> Can we keep neptune tag per system? because when you run a sweep you want each of the system have a different tag automatically without the need to set neptune tag in the cmd

We had an internal discussion: Since we have config.logger.system_name we can use it to filter the systems, no need to have different tags for different systems

**Review by OmaymaMahjoub — APPROVED** [review]
Thanks @RuanJohn :fire:

**Pull request merged**
