### PR TITLE
Feature: PettingZoo agent ids.

### LINKED ISSUE #732: [FEATURE] Agent ID in observations
Provide the option to add agent ID's to the observations in the JAX IPPO system.

### PR DESCRIPTION
**Pull request by DriesSmit**
## What?
Add functionality to optionally concatenate agent ids to PettingZoo environments. The Flatland and SMAC environment already has support for agent ids.
## Why?
This is to better benchmark against [this](https://arxiv.org/pdf/2103.01955.pdf) paper. 
## How?
Updated the PettingZoo `make_environment` function.
## Extra
Changed all the environments to by default not use agent ids.
Close #732

### CODE REVIEW

**Review by AsadJeewa — DISMISSED** [review]
Thanks @DriesSmit

**Review by siddarthsingh1 — DISMISSED** [review]
Thanks @DriesSmit!

**Comment by OmaymaMahjoub** [comment]
Waiting for benchmark

**Review by RuanJohn — DISMISSED** [review]
Benchmarking results can be found [here](https://www.notion.so/instadeep/Experiments-52346a5de10d444583896c8d5b026b25?p=d371ddc6072e4b9cabfb0297a71fe5b9&pm=s). TL;DR adding agent IDs do not lead to a regression in performance and the PR can be merged. Thank you @DriesSmit :tada:

**Review by arnupretorius — APPROVED** [review]
Thanks @DriesSmit :)

**Review by AsadJeewa — APPROVED** [review]
Thanks @DriesSmit

**Pull request merged**
