### PR TITLE
fix: sometimes logging 0 episode return

### PR DESCRIPTION
**Pull request by sash-a**
## What?
We were sometimes logging episode returns when our rollout length was too short to hit the end of an episode. Made sure we don't log these episodes.

### CODE REVIEW

**Review by liamclarkza — DISMISSED** [review]
Looks good

**Review by RuanJohn — CHANGES_REQUESTED** [review]
Looks good to me! Could you just please add this to the advanced usage systems as well?

**Review by liamclarkza — APPROVED** [review]
Looks good 👍

**Review by RuanJohn — APPROVED** [review]
LGTM

**Pull request merged**
