### PR TITLE
feat: change jumanji path

### PR DESCRIPTION
**Pull request by WiemKhlifi**
## What?
Change the path to Jumanji in the requirements file. 
## Why?
Since the original repo does not contain an LBF environment, this repo will serve us for the time being until LBF is merged into Jumanji.
## How?
Only modify the ` requirements.txt` file.

### CODE REVIEW

**Review by OmaymaMahjoub — CHANGES_REQUESTED** [review]
Thanks @WiemKhlifi!  can you also double check the quickstart notebook :pray:

**Review by RuanJohn — APPROVED** [review]
Thank you @WiemKhlifi :raised_hands:

**Comment by WiemKhlifi** [comment]
> Thank you @WiemKhlifi 🙌

My pleasure 🙌

**Review by OmaymaMahjoub — APPROVED** [review]
Thanks @WiemKhlifi :fire:

**Pull request merged**
