### PR TITLE
Bugfix/ Release aren't triggering pypi push job.

### PR DESCRIPTION
**Pull request by KaleabTessera**
## What?
Changed pypi job to be triggered whenever a release is `published` and not just `created`. For some reason, currently it appears that github thinks release 0.1.2 has ready been created and hence won't trigger the pypi job. Changing this to work on whenever a release is `released` seems better practice (https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#release , https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#release). 
## Why?
Release aren't triggering pypi push job.
## How?
-
## Extra
Seems related to this https://github.com/actions/starter-workflows/issues/554 .

### CODE REVIEW

**Review by arnupretorius — DISMISSED** [review]
Thanks @KaleabTessera 👍

**Review by RuanJohn — DISMISSED** [review]
Thanks @KaleabTessera :smile:

**Review by DriesSmit — APPROVED** [review]
Thanks @KaleabTessera :slightly_smiling_face:

**Review by DriesSmit — APPROVED** [review]

**Review by RuanJohn — APPROVED** [review]
Thank you @KaleabTessera :+1:

**Pull request merged**
