### PR TITLE
Feature/code coverage badge

### PR DESCRIPTION
**Pull request by arnupretorius**
## What?
Add code coverage to CI.
## Why?
To monitor ongoing changes in code coverage.
## How?
Use codecov app for github.

### CODE REVIEW

**Review by RuanJohn — COMMENTED** [review]
Thank you for adding this @arnupretorius :muscle: 
When I open the repo on this branch I can see the code coverage badge, but it shows that the coverage is unknown. Is this only for me?

**Comment by arnupretorius** [comment]
> Thank you for adding this @arnupretorius 💪 When I open the repo on this branch I can see the code coverage badge, but it shows that the coverage is unknown. Is this only for me?

It is because the badge link is set to the dev branch, if you swap it out for this PR branch you will see the coverage, currently at 92%. So once we merge this in, it should show up. 🙂

**Comment by arnupretorius** [comment]
> One final question I have that I can't seem to see from the code is whether we are computing the coverage percentage over the full testing suite (including system integration tests)?

We have a flag to toggle if we want to run integration tests or not, you can see this for example in the make file. If we choose to run integration tests, it seems it will run everything (integration + unit tests), otherwise it will just run unit tests. In both cases, a coverage report will be generated, uploaded to codecov and affect our coverage percentage on the badge. I guess what we can do, is only generate/update the coverage report when we run integration tests and display that, but part of reasoning for using codecov reporting was to track our coverage for each PR, and in that case we only run unit tests. That said, our unit test coverage is quite high (92% - given that we omit the wrappers etc.), so perhaps it is not too bad to only show unit test coverage. @KaleabTessera please also feel free to give your thoughts on this.

**Comment by arnupretorius** [comment]
> > One final question I have that I can't seem to see from the code is whether we are computing the coverage percentage over the full testing suite (including system integration tests)?
> 
> We have a flag to toggle if we want to run integration tests or not, you can see this for example in the make file. If we choose to run integration tests, it seems it will run everything (integration + unit tests), otherwise it will just run unit tests. In both cases, a coverage report will be generated, uploaded to codecov and affect our coverage percentage on the badge. I guess what we can do, is only generate/update the coverage report when we run integration tests and display that, but part of reasoning for using codecov reporting was to track our coverage for each PR, and in that case we only run unit tests. That said, our unit test coverage is quite high (92% - given that we omit the wrappers etc.), so perhaps it is not too bad to only show unit test coverage. @KaleabTessera please also feel free to give your thoughts on this.

Resolved in offline discussion.

**Review by RuanJohn — APPROVED** [review]
Thank you @arnupretorius :muscle: I look forward to seeing the badge on the repo :)

**Review by OmaymaMahjoub — APPROVED** [review]
Looks good thanks @arnupretorius, hope once we merge this PR, it will remove the unknown from the badge and it will show the code coverage :rocket:

**Pull request merged**
