### PR TITLE
Feature: Add Readme for setting up a new environment

### PR DESCRIPTION
**Pull request by DriesSmit**
## What?
Add a Readme to guide users on how to take a new environment and make it compatible with Mava.
## Why?
.
## How?
Add a Readme to the wrappers folder inside Mava.
## Extra

### CODE REVIEW

**Review by arnupretorius — APPROVED** [review]
Thanks @DriesSmit! 👍  I added some minor edits.

**Comment by arnupretorius** [comment]
Note: checks failing due to AutoRom, which will be fixed in this PR: #300

**Comment by KaleabTessera** [comment]
Looks great @DriesSmit !! Thanks for adding this.

**Review by KaleabTessera — DISMISSED** [review]

**Comment by DriesSmit** [comment]
> Looks great @DriesSmit !! Thanks for adding this.
> 
> Maybe add a pointer to this in the main readme here (https://github.com/instadeepai/Mava#supported-environments). Something like "For details on how to add your own environment, see (here)[link]".

Great idea @KaleabTessera  :+1: I added a reference in the main text.

**Review by arnupretorius — APPROVED** [review]
Thanks @DriesSmit 👍

**Pull request merged**
