### PR TITLE
refactor: move examples into tf folder and update examples links

### LINKED ISSUE #415: [MAINTAIN] Split example up into TF and Jax
### Please describe what needs to be maintained?
Move current examples into TF folder.

### PR DESCRIPTION
**Pull request by arnupretorius**
## What?
Move examples into TF folder.
## Why?
Separate current examples from future Jax examples.

closes #415

### CODE REVIEW

**Review by KaleabTessera — APPROVED** [review]
Thanks @arnupretorius  :+1:

**Review by AsadJeewa — APPROVED** [review]
Thanks Arnu

**Review by RuanJohn — APPROVED** [review]
Thanks @arnupretorius! :call_me_hand:

**Review by DriesSmit — APPROVED** [review]
Thanks @arnupretorius :smile:

**Pull request merged**
