### PR TITLE
Refactor the configs to mirror the structure of the python files

### PR DESCRIPTION
**Pull request by liamclarkza**
## What?
Small refactor that restructures the system config files to mirror the structure used for the python modules.

### CODE REVIEW

**Comment by EdanToledo** [comment]
I know that I'm just a community reviewer ;) but I'd like to just ask if one should reorganise the default config files as well? The problem persists that even if system configs are organised, as the algorithm variants increase the number of default configs will be very large as well.

**Comment by WiemKhlifi** [comment]
Hey @EdanToledo, you're right! We aim to fix this soon before the config folder explodes, please see issue #1033 😄

**Review by RuanJohn — APPROVED** [review]
Thanks @liamclarkza

**Review by WiemKhlifi — APPROVED** [review]
Thanks @liamclarkza 🙏

**Pull request merged**
