### PR TITLE
feat: Add fixed sampler capability + bugfixes

### PR DESCRIPTION
**Pull request by DriesSmit**
## What?
Add the capability to fix the sampler for MADDPG/MAD4PG. Also implemented bug fixes with @EdanToledo and @sash-a to get agents with different network architectures working in Mava.
## Why?
@EdanToledo and @sash-a would like the feature of having fixed networks for each agent, while each trainer only trains on one network.
## How?
Added a `fix_sampler` variable to the MADDPG/MAD4PG systems that allow a user to create a fixed sampling order for the agent networks.
## Extra
@sash-a and @EdanToledo please take a look at the new example and see if this would work for you?

### CODE REVIEW

**Review by sash-a — APPROVED** [review]
I still think `list_of_networks` is a bit of a vague name, but otherwise looks good

**Review by sash-a — APPROVED** [review]
Thanks for changing my nitpicky comment. All looks good :fire:

**Review by sash-a — APPROVED** [review]
Even better :fire:

**Review by KaleabTessera — APPROVED** [review]
Thanks @DriesSmit :open_hands:

**Pull request merged**
