### PR TITLE
Fix: maintain and fix the quickstart notebook

### PR DESCRIPTION
**Pull request by OmaymaMahjoub**
## What?
Maintain the quickstart notebook to support the latest jax, trained over the current jumanji rware ver and fix the evaluator code based on the recent changes to the repository

### CODE REVIEW

**Review by WiemKhlifi — DISMISSED** [review]
Thank you @OmaymaMahjoub for updating the notebook 🥳 

NIT:
1- In `render_one_episode` function, initialise `states` list as `states = [state]`.
2- In `plot_performance` function, remove the extra `f` in `plt.title(f'...')`
3- In run experiment section replace `for i` with `for _`

**Review by WiemKhlifi — APPROVED** [review]
LGTM 🥳

**Review by sash-a — APPROVED** [review]
Hard to review the notebook, but seems good to me :shrug:

**Comment by callumtilbury** [comment]
> Hard to review the notebook,

What do you mean, @sash-a? 🤔

**Comment by OmaymaMahjoub** [comment]
> > Hard to review the notebook,
> 
> What do you mean, @sash-a? 🤔

This is because it is tough to add the exact spot you want to add comments in a notebook

**Pull request merged**
