### PR TITLE
feat: auto reset wrapper

### PR DESCRIPTION
**Pull request by sash-a**
## What?
The jumanji auto reset wrapper has a small bug, this is a stop gap PR so that we have access to it until that on is merged: https://github.com/instadeepai/jumanji/pull/223

### CODE REVIEW

**Review by RuanJohn — DISMISSED** [review]
Looks good to me @sash-a! Super clean :muscle: 
Is this what you used for your SAC systems?

**Comment by sash-a** [comment]
> Looks good to me @sash-a! Super clean 💪 Is this what you used for your SAC systems?

Yup, hopefully will be in jumanji soon though

**Review by OmaymaMahjoub — APPROVED** [review]
LGTM! Thanks @sash-a

**Review by RuanJohn — APPROVED** [review]
:muscle:

**Pull request merged**
