### PR TITLE
fix: quickstart notebook

### LINKED ISSUE #1074: [BUG] Quickstart Colab imports failing
### Describe the bug
Running the Quickstart notebook fails to install the necessary dependencies, resulting in failed imports. `GlobalStateWrapper`,  `LearnerState`, and `evaluator_setup` seem to be the problems, but `AgentIDWrapper` and `RecordEpisodeMetrics ` imports do work.

### To Reproduce
```
27 from mava.wrappers.jumanji import RwareWrapper
---> 28 from mava.wrappers import AgentIDWrapper, GlobalStateWrapper, RecordEpisodeMetrics
     29 from mava.types import (
     30     ActorApply,

ImportError: cannot import name 'GlobalStateWrapper' from 'mava.wrappers' (/usr/local/lib/python3.10/dist-packages/mava/wrappers/__init__.py)
```
and same for ```from mava.types import (
    ActorApply,
    CriticApply,
    ExperimentOutput,
    LearnerFn,
    LearnerState,
    Observation,
    ObservationGlobalState,
    OptStates,
    Params,
    PPOTransition,
)```
```
ImportError: cannot import name 'LearnerState' from 'mava.types' (/usr/local/lib/python3.10/dist-packages/mava/types.py)
```
and `from mava.evaluator import evaluator_setup`: 
```
ImportError: cannot import name 'evaluator_setup' from 'mava.evaluator' (/usr/local/lib/python3.10/dist-packages/mava/evaluator.py)

```

### Expected behavior
imports occur without an issue.

### PR DESCRIPTION
**Pull request by WiemKhlifi**
## What?
Fix and update the quickstart notebook based on the new changes in the repo.
## Why?
The old code is outdated and we no longer use the `GlobalStateWrapper` or the _**vmapped**_ networks.

### CODE REVIEW

**Comment by sash-a** [comment]
Github not showing the changes, not sure how to review this :cry:

**Comment by WiemKhlifi** [comment]
I thought it would work by opening the PR in vscode locally but it doesn't 😢  
Two options are available here:
1- I shared a collab link for comments.
2- Quick meeting to show and explain the changes.
2- Download this notebook and replace the local notebook with this one to see the changes locally but it won't solve the reviewing problem 😢 -> Solution: Add the comments in the collab if you tried this.

**Review by sash-a — APPROVED** [review]
:rocket:

**Review by liamclarkza — APPROVED** [review]
LGTM

**Pull request merged**
